version: "3.8"
services:
  redis:
    image: redis:7.2.1
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  mongodb:
    image: mongo
    container_name: mongo
    env_file:
      - .env
    restart: always #never
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_ROOT_DATABASE=${MONGO_DB}
      - MONGO_DB_USERNAME=${MONGO_USERNAME}
      - MONGO_DB_PASSWORD=${MONGO_PASSWORD}
  mongo-express:
    image: mongo-express
    container_name: express
    env_file:
      - .env
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb:27017?authSource=admin
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_PASSWORD}