version: "3.8"
services:
  redis:
    image: redis:7.2.1
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  mongodb:
    image: mongo
    container_name: mongo
    env_file:
      - .env
    restart: always #never
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234
      - MONGO_INITDB_ROOT_DATABASE=cherry
      - MONGO_DB_USERNAME=root
      - MONGO_DB_PASSWORD=1234
  mongo-express:
    image: mongo-express
    container_name: express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1234
      ME_CONFIG_MONGODB_URL: mongodb://root:1234@mongodb:27017?authSource=admin
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: 1234