spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:cherry
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
      default_batch_fetch_size: 100
    open-in-view: false
    defer-datasource-initialization: true
  data:
    redis:
      jedis:
        pool:
          min-idle: 0
          max-idle: 8
          max-active: 8
      port: 6379
      host: 127.0.01
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

jwt:
  secret: Y2hlcnJ5aG91c2V3ZWJkZXZlbG9wbWVudDIwMjR3aW50ZXJwcm9qZWN0Y2hlcnJ5aG91c2V3ZWJkZXZlbG9wbWVudDIwMjR3aW50ZXJwcm9qZWN0